a = int(input("give a number:"))
b = int(input("give an another number:"))
print("a+b=",a+b)
print("a-b=",a-b)
print("a*b=",a*b)
print("a/b=",a/b)

print(a,"+", b ,"=", a+b)
print(a,"-", b ,"=", a-b)
print(a,"*", b , "=", a*b)
print(a,"/",b,"=",a/b)